version: '2'
services:
  mongodb:
    image: mongo:3.4
    command: mongod
    ports:
      - "27017:27017"
    volumes:
      - /data/mongodb:/data/db/
  heyburrito:
    env_file:
      - .env
    image: chralp/heyburrito:latest
    ports:
      - "3333:3333"
      - "3334:3334"
    links:
      - mongodb
